# Generated by Django 5.2.7 on 2025-10-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['tanggal_mulai']},
        ),
    ]
