# Generated by Django 5.2.7 on 2025-10-26 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_agenda_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['tanggal_mulai'], 'verbose_name': 'Agenda', 'verbose_name_plural': 'Agenda'},
        ),
        migrations.AddField(
            model_name='agenda',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dibuat Pada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='diperbarui_pada',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kategori',
            field=models.CharField(choices=[('akademik', 'Akademik'), ('non_akademik', 'Non-Akademik'), ('ekstrakurikuler', 'Ekstrakurikuler'), ('keagamaan', 'Keagamaan'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('rencana', 'Rencana'), ('berlangsung', 'Sedang Berlangsung'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='rencana', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='deskripsi',
            field=models.TextField(verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='judul',
            field=models.CharField(max_length=200, verbose_name='Judul Agenda'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='lokasi',
            field=models.CharField(max_length=200, verbose_name='Lokasi'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='pihak_terkait',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pihak Terkait'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tanggal_mulai',
            field=models.DateTimeField(verbose_name='Tanggal Mulai'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tanggal_selesai',
            field=models.DateTimeField(verbose_name='Tanggal Selesai'),
        ),
    ]
