# Generated by Django 5.2.7 on 2025-10-25 08:18

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', ckeditor.fields.RichTextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('tanggal_publikasi', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.CharField(choices=[('pengumuman', 'Pengumuman'), ('kegiatan', 'Kegiatan'), ('prestasi', 'Prestasi')], max_length=50)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
