# Generated by Django 5.2.7 on 2025-10-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'ordering': ['-tanggal_publikasi']},
        ),
    ]
