# Generated by Django 5.2.7 on 2025-11-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
