# Generated by Django 5.2.7 on 2025-10-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjek', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('sudah_dibaca', models.BooleanField(default=False)),
            ],
        ),
    ]
