# Generated by Django 5.2.7 on 2025-12-15 12:03

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriEdukasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='fas fa-book', help_text='Class FontAwesome, misal: fas fa-book', max_length=50)),
            ],
            options={
                'verbose_name': 'Kategori Edukasi',
                'verbose_name_plural': 'Kategori Edukasi',
            },
        ),
        migrations.CreateModel(
            name='MateriEdukasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('jenis', models.CharField(choices=[('artikel', 'Artikel/Bacaan'), ('video', 'Video')], default='artikel', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='edukasi/thumbnails/')),
                ('konten', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Untuk artikel', null=True)),
                ('video_url', models.URLField(blank=True, help_text='Link YouTube jika jenisnya Video', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='edukasi.kategoriedukasi')),
            ],
            options={
                'verbose_name': 'Materi Edukasi',
                'verbose_name_plural': 'Materi Edukasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
