# Generated by Django 5.2.7 on 2025-12-15 13:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriedukasi',
            name='icon',
            field=models.CharField(choices=[('fas fa-mosque', 'Masjid (Agama)'), ('fas fa-quran', 'Al-Quran'), ('fas fa-book-open', 'Buku/Bacaan'), ('fas fa-kaaba', "Ka'bah/Haji"), ('fas fa-pray', 'Orang Berdoa'), ('fas fa-star-and-crescent', 'Bulan Bintang'), ('fas fa-hands-helping', 'Adab/Akhlak'), ('fas fa-heart', 'Hati/Qolbu'), ('fas fa-video', 'Video'), ('fas fa-play-circle', 'Play Button'), ('fas fa-graduation-cap', 'Pendidikan'), ('fas fa-child', 'Anak-anak'), ('fas fa-users', 'Kisah Sahabat/Sosial'), ('fas fa-lightbulb', 'Inspirasi/Hikmah')], default='fas fa-book', help_text='Pilih ikon yang sesuai dengan kategori', max_length=50),
        ),
        migrations.AlterField(
            model_name='materiedukasi',
            name='konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiedukasi',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
